services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openlinks-app
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    networks:
      - openlinks
    depends_on:
      - otel-collector

  otel-collector:
    # Troque para a versão 'contrib'
    image: otel/opentelemetry-collector-contrib:latest
    container_name: openlinks-otel-collector
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    networks:
      - openlinks

  loki:
    image: grafana/loki:latest
    container_name: openlinks-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - openlinks

  grafana:
    image: grafana/grafana:latest
    container_name: openlinks-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - openlinks
    depends_on:
      - loki

  db:
    image: postgres:alpine
    container_name: openlinks-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-openlinks}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - openlinks-db:/var/lib/postgresql/data
    networks:
      - openlinks

networks:
  openlinks:

volumes:
  openlinks-db:
