service: my-app
image: my-user/my-app
ssh:
  user: root
  keys: ['~/.ssh/hetzner']
servers:
  web:
    - links.zapsecreto.com.br
proxy:
  ssl: true
  host: links.zapsecreto.com.br
  app_port: 80
  healthcheck:
    path: /up
registry:
  server: localhost:5555
builder:
  arch: amd64
aliases:
  shell: app exec --interactive --reuse "sh"
  tinker: app exec --interactive --reuse "php artisan tinker"
asset_path: /var/www/html/public/build
accessories:
  db:
    image: postgres:16-alpine
    host: links.zapsecreto.com.br
    port: 5432
    env:
      secret:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

  otel:
    image: otel/opentelemetry-collector-contrib:latest
    host: links.zapsecreto.com.br
    port: "4318:4318"
    cmd: --config=/etc/otel-collector-config.yaml
    files:
      - otel-config.yaml:/etc/otel-collector-config.yaml

  loki:
    image: grafana/loki:latest
    host: links.zapsecreto.com.br
    port: "127.0.0.1:3100:3100"
    cmd: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    host: links.zapsecreto.com.br
    port: "127.0.0.1:3000:3000"
    env:
      clear:
        GF_AUTH_ANONYMOUS_ENABLED: "false"
env:
  clear:
    APP_NAME: OpenLinks
    APP_ENV: production
    APP_DEBUG: false
    APP_URL: https://links.zapsecreto.com.br
    APP_DOMAIN: links.zapsecreto.com.br
    DB_CONNECTION: pgsql
    DB_HOST: my-app-db
    DB_PORT: 5432
    DB_DATABASE: openlinks
    DB_USERNAME: postgres
    LOG_CHANNEL: otel
    LOG_STACK: single
    LOG_LEVEL: error
    OTEL_PHP_AUTOLOAD_ENABLED: true
    OTEL_SERVICE_NAME: openlinks-web
    OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    OTEL_EXPORTER_OTLP_ENDPOINT: http://my-app-otel:4318
    OTEL_LOGS_EXPORTER: otlp
  secret:
    - APP_KEY
    - DB_PASSWORD
